import type { Product, Campaign } from "@/types/product";

const BASE = "https://images.unsplash.com";

export const products: Product[] = [
  // ── MODA FEMININA ────────────────────────────────────────────────────────────
  {
    id: "f1",
    name: "Vestido Midi Cetim",
    slug: "vestido-midi-cetim",
    description: "Vestido midi em cetim com decote elegante. Perfeito para eventos sofisticados.",
    price: 1290,
    originalPrice: 1590,
    category: "vestidos",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop`, alt: "Vestido Midi Cetim" }],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Champagne", "Preto"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["vestido", "cetim", "elegante"],
  },
  {
    id: "f2",
    name: "Blusa Seda Fluida",
    slug: "blusa-seda-fluida",
    description: "Blusa de seda com caimento impecável. Combine com calças ou saias.",
    price: 690,
    category: "blusas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1469334031218-e382a71b716b?w=600&h=800&fit=crop`, alt: "Blusa Seda Fluida" }],
    sizes: ["PP", "P", "M", "G", "GG"],
    colors: ["Off-White", "Nude", "Preto"],
    inStock: true,
    featured: true,
    isNew: false,
    tags: ["blusa", "seda", "leve"],
  },
  {
    id: "f3",
    name: "Calça Alfaiataria Slim",
    slug: "calca-alfaiataria-slim",
    description: "Calça de alfaiataria com modelagem slim. Versatilidade do dia à noite.",
    price: 890,
    category: "calças-femininas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1594938298603-c8148f4f0be4?w=600&h=800&fit=crop`, alt: "Calça Alfaiataria" }],
    sizes: ["34", "36", "38", "40", "42"],
    colors: ["Preto", "Marfim", "Caramelo"],
    inStock: true,
    featured: false,
    isNew: true,
    tags: ["calça", "alfaiataria", "trabalho"],
  },
  {
    id: "f4",
    name: "Saia Midi Plissada",
    slug: "saia-midi-plissada",
    description: "Saia midi plissada com movimento elegante. Ideal para looks femininos.",
    price: 750,
    originalPrice: 950,
    category: "saias",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1583496661160-fb5974ca5f3c?w=600&h=800&fit=crop`, alt: "Saia Midi Plissada" }],
    sizes: ["34", "36", "38", "40"],
    colors: ["Dourado", "Champagne", "Preto"],
    inStock: true,
    featured: true,
    isNew: false,
    tags: ["saia", "plissada", "elegante"],
  },
  {
    id: "f5",
    name: "Vestido Longo Festa",
    slug: "vestido-longo-festa",
    description: "Vestido longo para noite. Decote em V e fenda lateral sutil.",
    price: 2190,
    category: "vestidos",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop`, alt: "Vestido Longo Festa" }],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Preto", "Vinho"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["vestido", "festa", "noite"],
  },
  {
    id: "f6",
    name: "Conjunto Linho Premium",
    slug: "conjunto-linho-premium",
    description: "Conjunto de blazer e calça em linho premium. Sofisticação natural.",
    price: 1490,
    category: "calças-femininas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1551488831-00ddcb6c6bd3?w=600&h=800&fit=crop`, alt: "Conjunto Linho" }],
    sizes: ["P", "M", "G", "GG"],
    colors: ["Cru", "Bege", "Cinza"],
    inStock: true,
    featured: false,
    isNew: true,
    tags: ["conjunto", "linho", "trabalho"],
  },
  {
    id: "f7",
    name: "Blusa Rendada Exclusiva",
    slug: "blusa-rendada-exclusiva",
    description: "Blusa com detalhes em renda artesanal. Peça exclusiva da coleção.",
    price: 890,
    category: "blusas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1585128792020-803d29415281?w=600&h=800&fit=crop`, alt: "Blusa Rendada" }],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Off-White", "Champagne"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["blusa", "renda", "exclusivo"],
  },
  {
    id: "f8",
    name: "Saia Assimétrica Couture",
    slug: "saia-assimetrica-couture",
    description: "Saia assimétrica com corte diagonal. Design de vanguarda.",
    price: 980,
    category: "saias",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1509631179647-0177331693ae?w=600&h=800&fit=crop`, alt: "Saia Assimétrica" }],
    sizes: ["34", "36", "38", "40"],
    colors: ["Preto", "Dourado"],
    inStock: false,
    featured: false,
    isNew: false,
    tags: ["saia", "design", "moderno"],
  },

  // ── MODA MASCULINA ────────────────────────────────────────────────────────────
  {
    id: "m1",
    name: "Blazer Estruturado",
    slug: "blazer-estruturado",
    description: "Blazer com estrutura impecável. Alfaiataria italiana sob medida.",
    price: 1890,
    category: "blazers",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1617196034183-421b4040ed20?w=600&h=800&fit=crop`, alt: "Blazer Estruturado" }],
    sizes: ["48", "50", "52", "54", "56"],
    colors: ["Preto", "Carvão", "Navy"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["blazer", "alfaiataria", "formal"],
  },
  {
    id: "m2",
    name: "Camisa Social Premium",
    slug: "camisa-social-premium",
    description: "Camisa em algodão egípcio de fio duplo. Conforto e elegância.",
    price: 590,
    category: "camisas",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop`, alt: "Camisa Social" }],
    sizes: ["P", "M", "G", "GG", "XGG"],
    colors: ["Branco", "Azul Claro", "Preto"],
    inStock: true,
    featured: true,
    isNew: false,
    tags: ["camisa", "algodão", "elegante"],
  },
  {
    id: "m3",
    name: "Calça Alfaiataria Clássica",
    slug: "calca-alfaiataria-classica",
    description: "Calça de alfaiataria clássica com caimento perfeito.",
    price: 890,
    originalPrice: 1090,
    category: "calças-masculinas",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1600486913747-55e5470d6f40?w=600&h=800&fit=crop`, alt: "Calça Alfaiataria" }],
    sizes: ["40", "42", "44", "46", "48"],
    colors: ["Carvão", "Preto", "Marinho"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["calça", "alfaiataria", "clássico"],
  },
  {
    id: "m4",
    name: "Camisa Linho Verão",
    slug: "camisa-linho-verao",
    description: "Camisa em linho puro para os dias quentes. Estilo sem abrir mão do conforto.",
    price: 490,
    category: "camisas",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1519085360753-af0119f7cbe7?w=600&h=800&fit=crop`, alt: "Camisa Linho" }],
    sizes: ["P", "M", "G", "GG"],
    colors: ["Bege", "Off-White", "Azul Claro"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["camisa", "linho", "verão"],
  },
  {
    id: "m5",
    name: "Blazer Casual Moderno",
    slug: "blazer-casual-moderno",
    description: "Blazer com toque casual. Perfeito para o look business casual.",
    price: 1490,
    category: "blazers",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1602810318383-e386cc2a3ccf?w=600&h=800&fit=crop`, alt: "Blazer Casual" }],
    sizes: ["48", "50", "52", "54"],
    colors: ["Bege", "Cinza Claro", "Caramelo"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["blazer", "casual", "moderno"],
  },
  {
    id: "m6",
    name: "Polo Tricot Luxo",
    slug: "polo-tricot-luxo",
    description: "Polo em tricot de caxemira. Sofisticação no detalhe.",
    price: 790,
    category: "camisas",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1580651315530-69c8e0026377?w=600&h=800&fit=crop`, alt: "Polo Tricot" }],
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Navy", "Vinho"],
    inStock: true,
    featured: false,
    isNew: true,
    tags: ["polo", "tricot", "caxemira"],
  },
  {
    id: "m7",
    name: "Terno Slim Completo",
    slug: "terno-slim-completo",
    description: "Terno slim em lã italiana. Corte moderno e acabamento impecável.",
    price: 3490,
    category: "blazers",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1539185441755-769473a23570?w=600&h=800&fit=crop`, alt: "Terno Slim" }],
    sizes: ["48", "50", "52", "54", "56"],
    colors: ["Preto", "Carvão", "Azul Marinho"],
    inStock: true,
    featured: true,
    isNew: false,
    tags: ["terno", "lã", "formal"],
  },
  {
    id: "m8",
    name: "Calça Chino Premium",
    slug: "calca-chino-premium",
    description: "Calça chino em sarja premium. Do escritório ao jantar.",
    price: 690,
    category: "calças-masculinas",
    gender: "masculino",
    images: [{ url: `${BASE}/photo-1473966968600-fa801b869a1a?w=600&h=800&fit=crop`, alt: "Calça Chino" }],
    sizes: ["40", "42", "44", "46"],
    colors: ["Caqui", "Cinza", "Preto"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["calça", "chino", "casual"],
  },

  // ── BOLSAS & ACESSÓRIOS ───────────────────────────────────────────────────────
  {
    id: "b1",
    name: "Bolsa Tote Couro",
    slug: "bolsa-tote-couro",
    description: "Bolsa tote em couro genuíno. Espaçosa, elegante e atemporal.",
    price: 2490,
    category: "bolsas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop`, alt: "Bolsa Tote Couro" }],
    sizes: ["Único"],
    colors: ["Preto", "Caramelo", "Cognac"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["bolsa", "couro", "tote"],
  },
  {
    id: "b2",
    name: "Clutch Metálica",
    slug: "clutch-metalica",
    description: "Clutch metálica para noite. Detalhe dourado que transforma o look.",
    price: 890,
    category: "bolsas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1591561954557-26941169b49e?w=600&h=600&fit=crop`, alt: "Clutch Metálica" }],
    sizes: ["Único"],
    colors: ["Dourado", "Prata", "Bronze"],
    inStock: true,
    featured: true,
    isNew: true,
    tags: ["clutch", "festa", "dourado"],
  },
  {
    id: "b3",
    name: "Bolsa Shoulder Mini",
    slug: "bolsa-shoulder-mini",
    description: "Mini shoulder bag em couro saffiano. Compacta e refinada.",
    price: 1690,
    originalPrice: 1990,
    category: "bolsas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1584917865442-de89df76afd3?w=600&h=600&fit=crop`, alt: "Shoulder Mini" }],
    sizes: ["Único"],
    colors: ["Preto", "Nude", "Bordô"],
    inStock: true,
    featured: true,
    isNew: false,
    tags: ["bolsa", "mini", "couro"],
  },
  {
    id: "b4",
    name: "Cinto Couro Dourado",
    slug: "cinto-couro-dourado",
    description: "Cinto em couro com fivela dourada. O acabamento que eleva qualquer look.",
    price: 490,
    category: "cintos",
    gender: "unissex",
    images: [{ url: `${BASE}/photo-1553062407-98eeb64c6a62?w=600&h=400&fit=crop`, alt: "Cinto Dourado" }],
    sizes: ["P", "M", "G"],
    colors: ["Preto/Dourado", "Caramelo/Dourado"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["cinto", "couro", "dourado"],
  },
  {
    id: "b5",
    name: "Óculos Cat Eye Premium",
    slug: "oculos-cat-eye",
    description: "Óculos de sol cat eye com armação acetato italiana. Ícone de estilo.",
    price: 790,
    category: "acessórios",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1511499767150-a48a237f0083?w=600&h=400&fit=crop`, alt: "Óculos Cat Eye" }],
    sizes: ["Único"],
    colors: ["Tartaruga", "Preto", "Nude"],
    inStock: true,
    featured: false,
    isNew: true,
    tags: ["óculos", "sol", "cat eye"],
  },
  {
    id: "b6",
    name: "Bolsa Bucket Camurça",
    slug: "bolsa-bucket-camurca",
    description: "Bucket bag em camurça premium. Casual chic para o dia a dia.",
    price: 1890,
    category: "bolsas",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1566150905458-1bf1fc113f0d?w=600&h=600&fit=crop`, alt: "Bolsa Bucket" }],
    sizes: ["Único"],
    colors: ["Caramelo", "Preto", "Nude"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["bolsa", "bucket", "camurça"],
  },
  {
    id: "b7",
    name: "Lenço Seda Estampado",
    slug: "lenco-seda-estampado",
    description: "Lenço em seda com estampa exclusiva. Use no pescoço, na bolsa ou no cabelo.",
    price: 390,
    category: "acessórios",
    gender: "feminino",
    images: [{ url: `${BASE}/photo-1506629082955-511b1aa562c8?w=600&h=400&fit=crop`, alt: "Lenço Seda" }],
    sizes: ["90x90cm"],
    colors: ["Dourado/Preto", "Champagne/Nude"],
    inStock: true,
    featured: false,
    isNew: true,
    tags: ["lenço", "seda", "acessório"],
  },
  {
    id: "b8",
    name: "Carteira Couro Slim",
    slug: "carteira-couro-slim",
    description: "Carteira slim em couro italiano com compartimentos inteligentes.",
    price: 590,
    category: "acessórios",
    gender: "unissex",
    images: [{ url: `${BASE}/photo-1627123424574-724758594785?w=600&h=400&fit=crop`, alt: "Carteira Couro" }],
    sizes: ["Único"],
    colors: ["Preto", "Cognac", "Bordô"],
    inStock: true,
    featured: false,
    isNew: false,
    tags: ["carteira", "couro", "slim"],
  },
];

export const campaigns: Campaign[] = [
  {
    id: "c1",
    title: "Inverno Dourado",
    subtitle: "Coleção Inverno 2025",
    description:
      "Peças que traduzem o requinte do frio com tecidos nobres e silhuetas modernas. Uma celebração da elegância em cada detalhe.",
    image: `${BASE}/photo-1558769132-cb1aea458c5e?w=1200&h=700&fit=crop`,
    cta: "Explorar Coleção",
    ctaHref: "/moda-feminina",
    season: "Inverno",
    year: 2025,
    featured: true,
  },
  {
    id: "c2",
    title: "Homem Moderno",
    subtitle: "Campanha Masculina 2025",
    description:
      "Para o homem que valoriza estilo e substância. Alfaiataria contemporânea que equilibra sofisticação e conforto.",
    image: `${BASE}/photo-1490114538077-0a7f8cb49891?w=1200&h=700&fit=crop`,
    cta: "Ver Coleção",
    ctaHref: "/moda-masculina",
    season: "Verão",
    year: 2025,
    featured: false,
  },
  {
    id: "c3",
    title: "It Bags",
    subtitle: "Bolsas & Acessórios 2025",
    description:
      "A bolsa certa não apenas completa o look — ela o define. Descubra nossa curadoria de bolsas e acessórios premium.",
    image: `${BASE}/photo-1483985988355-763728e1935b?w=1200&h=700&fit=crop`,
    cta: "Descobrir",
    ctaHref: "/bolsas-acessorios",
    season: "Atemporal",
    year: 2025,
    featured: false,
  },
];

export function getProductsByGender(gender: "feminino" | "masculino") {
  return products.filter((p) => p.gender === gender || p.gender === "unissex");
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getBagsAndAccessories() {
  return products.filter((p) =>
    ["bolsas", "acessórios", "cintos"].includes(p.category)
  );
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}
